repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
        args: [--assume-in-merge]
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
#    -   id: no-commit-to-branch
#         Use args: [--branch, staging, --branch, main] to set the branch. Both main and master are protected by default if no branch argument is set.
#         -b / --branch may be specified multiple times to protect multiple branches.
#         -p / --pattern can be used to protect branches that match a supplied regex (e.g. --pattern, release/.*). May be specified multiple times.
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy

#        args: [--no-strict-optional, --ignore-missing-imports]
#        additional_dependencies: [tokenize-rt==3.2.0]

# -   repo: git://github.com/FalconSocial/pre-commit-python-sorter
#     sha: 1.0.4
#     hooks:
#     -   id: python-import-sorter
#         args: ['--check-only']
# #       args: ['--silent-overwrite']

# -   repo: git://github.com/guykisel/prospector-mirror
#     rev: v0.8
#     hooks:
#     -   id: prospector
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
